apiVersion: v1
kind: Namespace
metadata:
  annotations:
    workload.openshift.io/allowed: "management"
  labels:
    app.kubernetes.io/name: ksan-storage-operator
    security.openshift.io/scc.podSecurityLabelSync: "false"
    pod-security.kubernetes.io/enforce: "privileged"
    pod-security.kubernetes.io/warn: "privileged"
    pod-security.kubernetes.io/audit: "privileged"
    openshift.io/cluster-monitoring: "true"
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
  labels:
    app.kubernetes.io/name: ksan-storage-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ksan-storage-operator
  replicas: 1
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app.kubernetes.io/name: ksan-storage-operator
        app.kubernetes.io/part-of: ksan-storage
        app.kubernetes.io/component: ksan-storage-operator
    spec:
      securityContext:
        runAsNonRoot: true
      priorityClassName: openshift-user-critical
      containers:
      - command:
        - /ksan-storage
        - operator
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=:8443
        image: controller:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 5m
            memory: 50Mi
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      serviceAccountName: ksan-storage-operator
      terminationGracePeriodSeconds: 10