apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: ksan
    app.kubernetes.io/managed-by: kustomize
  name: daemon-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: daemon-role
subjects:
  - kind: ServiceAccount
    name: ksan-storage-nodedaemon
    namespace: system
